### ISSUE TITLE
表のスタイル崩れ

### ISSUE THREAD

**Issue by ishikawa1027** [hifivemania/deviceconnect-handson#1]
https://github.com/hifivemania/deviceconnect-handson/blob/master/5.md

ページ中段（PUT /gotapi/vibration/vibrate）と下部の表がMDの表として認識されておらず、崩れています。

**Comment by goofmint** [comment]
更新しました！

**Comment by ishikawa1027** [comment]
確認しました。
ページ最下部の表も同じ崩れ方をしているので、そちらの修正もお願いします。

**Comment by goofmint** [comment]
失礼しました。GitHubの解釈は普通のと違いますね…。修正しました。

**Comment by ishikawa1027** [comment]
確認しました！
