### ISSUE TITLE
コードスタイル崩れ

### ISSUE THREAD

**Issue by ishikawa1027** [hifivemania/deviceconnect-handson#4]
https://github.com/hifivemania/deviceconnect-handson/blob/8f03c840428224e18d05b29e51c48ea01db5f074/4/javascripts/app.js#L167

関数の括弧の前はスペースを詰めてください。
（4～7章のソースの同じ箇所を要修正）

```JavaScript
    // 誤
    '#vibrate click': function (e) {
    }
    // 正
    '#vibrate click': function(e) {
    }
```

**Comment by goofmint** [comment]
更新しました

**Comment by ishikawa1027** [comment]
LGTMです！
