### ISSUE TITLE
変数定義にvarが無い

### ISSUE THREAD

**Issue by ishikawa1027** [hifivemania/deviceconnect-handson#5]
https://github.com/hifivemania/deviceconnect-handson/blob/90399af49940b9acbdd940fbecff0964e64e4e70/4/javascripts/app.js#L104

スコープ漏れをふせぐためにvarを付けて下さい。
（4~7章で同様の修正）

```JavaScript
    // NG
      for (i in this.__services) {}

    // OK
      for (var i in this.__services) {}
```

**Comment by goofmint** [comment]
修正しました。

**Comment by ishikawa1027** [comment]
確認しました。6章、7章も同じく修正おねがいします。

**Comment by goofmint** [comment]
すみません、コミットが漏れていました…。

**Comment by ishikawa1027** [comment]
確認しました！
